set_property IOSTANDARD LVCMOS33 [get_ports o_TxSerial]
set_property PACKAGE_PIN D14 [get_ports o_TxSerial]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rx_Serial]
set_property PACKAGE_PIN F16 [get_ports i_Rx_Serial]
set_property IOSTANDARD LVCMOS33 [get_ports o_Enable]
set_property PACKAGE_PIN G16 [get_ports o_Enable]
set_property IOSTANDARD LVCMOS33 [get_ports o_TxTri]
set_property PACKAGE_PIN H14 [get_ports o_TxTri]
set_property IOSTANDARD LVCMOS33 [get_ports SystemClk_100MHz]
set_property PACKAGE_PIN E3 [get_ports SystemClk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports SystemRst]
set_property PACKAGE_PIN C12 [get_ports SystemRst]
set_property IOSTANDARD LVCMOS33 [get_ports i_Switch]
set_property PACKAGE_PIN V10 [get_ports i_Switch]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Rx_Byte[0]}]
set_property PACKAGE_PIN V12 [get_ports {o_Rx_Byte[7]}]
set_property PACKAGE_PIN A8 [get_ports {o_Rx_Byte[5]}]
set_property PACKAGE_PIN U14 [get_ports {o_Rx_Byte[4]}]
set_property PACKAGE_PIN V14 [get_ports {o_Rx_Byte[3]}]
set_property PACKAGE_PIN T13 [get_ports {o_Rx_Byte[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Tx_Byte[0]}]
set_property PACKAGE_PIN V16 [get_ports {o_Tx_Byte[7]}]
set_property PACKAGE_PIN U17 [get_ports {o_Tx_Byte[6]}]
set_property PACKAGE_PIN U18 [get_ports {o_Tx_Byte[5]}]
set_property PACKAGE_PIN U16 [get_ports {o_Tx_Byte[4]}]
set_property PACKAGE_PIN V17 [get_ports {o_Tx_Byte[3]}]
set_property PACKAGE_PIN U11 [get_ports {o_Tx_Byte[1]}]
set_property PACKAGE_PIN U12 [get_ports {o_Tx_Byte[0]}]

set_property PACKAGE_PIN V11 [get_ports {o_Rx_Byte[6]}]






set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_Delay[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentAnode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_SegmentCathode[0]}]
set_property PACKAGE_PIN R11 [get_ports {o_Delay[31]}]
set_property PACKAGE_PIN K17 [get_ports {o_Delay[30]}]
set_property PACKAGE_PIN K18 [get_ports {o_Delay[29]}]
set_property PACKAGE_PIN L14 [get_ports {o_Delay[28]}]
set_property PACKAGE_PIN M14 [get_ports {o_Delay[27]}]
set_property PACKAGE_PIN L15 [get_ports {o_Delay[26]}]
set_property PACKAGE_PIN R12 [get_ports {o_Delay[23]}]
set_property PACKAGE_PIN R13 [get_ports {o_Delay[22]}]
set_property PACKAGE_PIN L13 [get_ports {o_Delay[21]}]
set_property PACKAGE_PIN M13 [get_ports {o_Delay[20]}]
set_property PACKAGE_PIN R18 [get_ports {o_Delay[19]}]
set_property PACKAGE_PIN T18 [get_ports {o_Delay[18]}]
set_property PACKAGE_PIN N14 [get_ports {o_Delay[17]}]
set_property PACKAGE_PIN N17 [get_ports {o_Delay[15]}]
set_property PACKAGE_PIN M16 [get_ports {o_Delay[14]}]
set_property PACKAGE_PIN M17 [get_ports {o_Delay[13]}]
set_property PACKAGE_PIN N15 [get_ports {o_Delay[12]}]
set_property PACKAGE_PIN N16 [get_ports {o_Delay[11]}]
set_property PACKAGE_PIN P17 [get_ports {o_Delay[10]}]
set_property PACKAGE_PIN R17 [get_ports {o_Delay[9]}]
set_property PACKAGE_PIN R15 [get_ports {o_Delay[7]}]
set_property PACKAGE_PIN T15 [get_ports {o_Delay[5]}]
set_property PACKAGE_PIN R16 [get_ports {o_Delay[4]}]
set_property PACKAGE_PIN T16 [get_ports {o_Delay[3]}]
set_property PACKAGE_PIN V15 [get_ports {o_Delay[2]}]
set_property PACKAGE_PIN J17 [get_ports {o_SegmentAnode[0]}]
set_property PACKAGE_PIN J18 [get_ports {o_SegmentAnode[1]}]
set_property PACKAGE_PIN T9 [get_ports {o_SegmentAnode[2]}]
set_property PACKAGE_PIN J14 [get_ports {o_SegmentAnode[3]}]
set_property PACKAGE_PIN P14 [get_ports {o_SegmentAnode[4]}]
set_property PACKAGE_PIN T14 [get_ports {o_SegmentAnode[5]}]
set_property PACKAGE_PIN K2 [get_ports {o_SegmentAnode[6]}]
set_property PACKAGE_PIN U13 [get_ports {o_SegmentAnode[7]}]
set_property PACKAGE_PIN T10 [get_ports {o_SegmentCathode[0]}]
set_property PACKAGE_PIN R10 [get_ports {o_SegmentCathode[1]}]
set_property PACKAGE_PIN K16 [get_ports {o_SegmentCathode[2]}]
set_property PACKAGE_PIN K13 [get_ports {o_SegmentCathode[3]}]
set_property PACKAGE_PIN P15 [get_ports {o_SegmentCathode[4]}]
set_property PACKAGE_PIN T11 [get_ports {o_SegmentCathode[5]}]
set_property PACKAGE_PIN L18 [get_ports {o_SegmentCathode[6]}]
set_property PACKAGE_PIN H15 [get_ports {o_SegmentCathode[7]}]
set_property PACKAGE_PIN A11 [get_ports {o_Delay[24]}]
set_property PACKAGE_PIN A9 [get_ports {o_Delay[16]}]
set_property PACKAGE_PIN A4 [get_ports {o_Delay[8]}]
set_property PACKAGE_PIN A1 [get_ports {o_Delay[6]}]
set_property PACKAGE_PIN A6 [get_ports {o_Delay[1]}]
set_property PACKAGE_PIN A16 [get_ports {o_Delay[0]}]
set_property PACKAGE_PIN B9 [get_ports {o_Tx_Byte[2]}]
set_property PACKAGE_PIN B11 [get_ports {o_Rx_Byte[1]}]
set_property PACKAGE_PIN B13 [get_ports {o_Rx_Byte[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports i_DecSwitch]
set_property IOSTANDARD LVCMOS33 [get_ports i_IncSwitch]
set_property PACKAGE_PIN L16 [get_ports i_IncSwitch]
set_property PACKAGE_PIN J15 [get_ports i_DecSwitch]
set_property PACKAGE_PIN A10 [get_ports {o_Delay[25]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clocks_instance/inst/clk_100MHz]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {storageTx/r_Contador_reg[1]} {storageTx/r_Contador_reg[2]} {storageTx/r_Contador_reg[3]} {storageTx/r_Contador_reg[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {o_Tx_Byte_OBUF[0]} {o_Tx_Byte_OBUF[1]} {o_Tx_Byte_OBUF[2]} {o_Tx_Byte_OBUF[3]} {o_Tx_Byte_OBUF[4]} {o_Tx_Byte_OBUF[5]} {o_Tx_Byte_OBUF[6]} {o_Tx_Byte_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list i_Switch_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list storageTx/r_Dir]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list o_Enable_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets w_Clk100MHz]
